/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var a=this||self,b=function(g,k){g=g.split(".");for(var f=a,e;g.length&&(e=g.shift());)g.length||k===void 0?f=f[e]&&f[e]!==Object.prototype[e]?f[e]:f[e]={}:f[e]=k};var c={j:{1E3:{other:"0K"},1E4:{other:"00K"},1E5:{other:"000K"},1E6:{other:"0M"},1E7:{other:"00M"},1E8:{other:"000M"},1E9:{other:"0B"},1E10:{other:"00B"},1E11:{other:"000B"},1E12:{other:"0T"},1E13:{other:"00T"},1E14:{other:"000T"}},i:{1E3:{other:"0 thousand"},1E4:{other:"00 thousand"},1E5:{other:"000 thousand"},1E6:{other:"0 million"},1E7:{other:"00 million"},1E8:{other:"000 million"},1E9:{other:"0 billion"},1E10:{other:"00 billion"},1E11:{other:"000 billion"},1E12:{other:"0 trillion"},1E13:{other:"00 trillion"},
1E14:{other:"000 trillion"}}};
c={j:{1E3:{other:"0\u00a0k"},1E4:{other:"00\u00a0k"},1E5:{other:"000\u00a0k"},1E6:{other:"0\u00a0M"},1E7:{other:"00\u00a0M"},1E8:{other:"000\u00a0M"},1E9:{other:"0000\u00a0M"},1E10:{other:"00\u00a0kM"},1E11:{other:"000\u00a0kM"},1E12:{other:"0\u00a0B"},1E13:{other:"00\u00a0B"},1E14:{other:"000\u00a0B"}},i:{1E3:{other:"0 milers"},1E4:{other:"00 milers"},1E5:{other:"000 milers"},1E6:{other:"0 milions"},1E7:{other:"00 milions"},1E8:{other:"000 milions"},1E9:{other:"0 milers de milions"},1E10:{other:"00 milers de milions"},
1E11:{other:"000 milers de milions"},1E12:{other:"0 bilions"},1E13:{other:"00 bilions"},1E14:{other:"000 bilions"}}};var d={na:"y",va:"y G",oa:"MMM y",pa:"MMMM y",wa:"MM/y",M:"MMM d",N:"MMMM dd",P:"M/d",O:"MMMM d",sa:"MMM d, y",la:"EEE, MMM d",ta:"EEEE, MMMM d",ua:"EEE, MMM d, y",u:"d",ra:"MMM d, h:mm\u202fa zzzz"};d={na:"y",va:"y G",oa:"LLL 'del' y",pa:"LLLL 'del' y",wa:"MM/y",M:"d MMM",N:"dd MMMM",P:"d/M",O:"d MMMM",sa:"d MMM 'del' y",la:"EEE, d MMM",ta:"EEEE, d MMMM",ua:"EEE, d MMM y",u:"d",ra:"d MMM, H:mm zzzz"};var h={D:["BC","AD"],C:["Before Christ","Anno Domini"],S:"JFMAMJJASOND".split(""),ea:"JFMAMJJASOND".split(""),L:"January February March April May June July August September October November December".split(" "),da:"January February March April May June July August September October November December".split(" "),aa:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),ga:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),ka:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
ia:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),ca:"Sun Mon Tue Wed Thu Fri Sat".split(" "),ha:"Sun Mon Tue Wed Thu Fri Sat".split(" "),T:"SMTWTFS".split(""),fa:"SMTWTFS".split(""),ba:["Q1","Q2","Q3","Q4"],Y:["1st quarter","2nd quarter","3rd quarter","4th quarter"],h:["AM","PM"],m:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],ja:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],o:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],G:6,ma:[5,
6],H:5};
h={D:["aC","dC"],C:["abans de Crist","despr\u00e9s de Crist"],S:"GN FB M\u00c7 AB MG JN JL AG ST OC NV DS".split(" "),ea:"GN FB M\u00c7 AB MG JN JL AG ST OC NV DS".split(" "),L:"de gener;de febrer;de mar\u00e7;d\u2019abril;de maig;de juny;de juliol;d\u2019agost;de setembre;d\u2019octubre;de novembre;de desembre".split(";"),da:"gener febrer mar\u00e7 abril maig juny juliol agost setembre octubre novembre desembre".split(" "),aa:"de gen.;de febr.;de mar\u00e7;d\u2019abr.;de maig;de juny;de jul.;d\u2019ag.;de set.;d\u2019oct.;de nov.;de des.".split(";"),ga:"gen. febr. mar\u00e7 abr. maig juny jul. ag. set. oct. nov. des.".split(" "),
ka:"diumenge dilluns dimarts dimecres dijous divendres dissabte".split(" "),ia:"diumenge dilluns dimarts dimecres dijous divendres dissabte".split(" "),ca:"dg. dl. dt. dc. dj. dv. ds.".split(" "),ha:"dg. dl. dt. dc. dj. dv. ds.".split(" "),T:"dg. dl. dt. dc. dj. dv. ds.".split(" "),fa:"dg. dl. dt. dc. dj. dv. ds.".split(" "),ba:["1T","2T","3T","4T"],Y:["1r trimestre","2n trimestre","3r trimestre","4t trimestre"],h:["a.\u202fm.","p.\u202fm."],m:["EEEE, d MMMM 'del' y","d MMMM 'del' y","d MMM y","d/M/yy"],
ja:["H:mm:ss (zzzz)","H:mm:ss z","H:mm:ss","H:mm"],o:["{1}, 'a' 'les' {0}","{1}, 'a' 'les' {0}","{1}, {0}","{1} {0}"],G:0,ma:[5,6],H:3};var l={A:".",I:",",U:"%",qa:"0",X:"+",K:"-",F:"E",W:"\u2030",J:"\u221e",R:"NaN",v:"#,##0.###",Z:"#E0",V:"#,##0%",l:"\u00a4#,##0.00",B:"USD"};l={A:",",I:".",U:"%",qa:"0",X:"+",K:"-",F:"E",W:"\u2030",J:"\u221e",R:"NaN",v:"#,##0.###",Z:"#E0",V:"#,##0\u00a0%",l:"#,##0.00\u00a0\u00a4",B:"EUR"};b("I18N_DATETIMESYMBOLS_ERAS",h.D);b("I18N_DATETIMESYMBOLS_ERANAMES",h.C);b("I18N_DATETIMESYMBOLS_NARROWMONTHS",h.S);b("I18N_DATETIMESYMBOLS_STANDALONENARROWMONTHS",h.ea);b("I18N_DATETIMESYMBOLS_MONTHS",h.L);b("I18N_DATETIMESYMBOLS_STANDALONEMONTHS",h.da);b("I18N_DATETIMESYMBOLS_SHORTMONTHS",h.aa);b("I18N_DATETIMESYMBOLS_STANDALONESHORTMONTHS",h.ga);b("I18N_DATETIMESYMBOLS_WEEKDAYS",h.ka);b("I18N_DATETIMESYMBOLS_STANDALONEWEEKDAYS",h.ia);b("I18N_DATETIMESYMBOLS_SHORTWEEKDAYS",h.ca);
b("I18N_DATETIMESYMBOLS_STANDALONESHORTWEEKDAYS",h.ha);b("I18N_DATETIMESYMBOLS_NARROWWEEKDAYS",h.T);b("I18N_DATETIMESYMBOLS_STANDALONENARROWWEEKDAYS",h.fa);b("I18N_DATETIMESYMBOLS_SHORTQUARTERS",h.ba);b("I18N_DATETIMESYMBOLS_QUARTERS",h.Y);b("I18N_DATETIMESYMBOLS_AMPMS",h.h);b("I18N_DATETIMESYMBOLS_DATEFORMATS",h.m);b("I18N_DATETIMESYMBOLS_TIMEFORMATS",h.ja);b("I18N_DATETIMESYMBOLS_DATETIMEFORMATS",h.o);b("I18N_DATETIMESYMBOLS_FIRSTDAYOFWEEK",h.G);b("I18N_DATETIMESYMBOLS_WEEKENDRANGE",h.ma);
b("I18N_DATETIMESYMBOLS_FIRSTWEEKCUTOFFDAY",h.H);b("I18N_DATETIMEPATTERNS_YEAR_FULL",d.na);b("I18N_DATETIMEPATTERNS_YEAR_MONTH_ABBR",d.oa);b("I18N_DATETIMEPATTERNS_YEAR_MONTH_FULL",d.pa);b("I18N_DATETIMEPATTERNS_MONTH_DAY_ABBR",d.M);b("I18N_DATETIMEPATTERNS_MONTH_DAY_FULL",d.N);b("I18N_DATETIMEPATTERNS_MONTH_DAY_SHORT",d.P);b("I18N_DATETIMEPATTERNS_MONTH_DAY_MEDIUM",d.O);b("I18N_DATETIMEPATTERNS_WEEKDAY_MONTH_DAY_MEDIUM",d.la);b("I18N_DATETIMEPATTERNS_DAY_ABBR",d.u);
h.xa!==void 0&&b("I18N_DATETIMESYMBOLS_ZERODIGIT",h.xa);b("I18N_NUMBERFORMATSYMBOLS_DECIMAL_SEP",l.A);b("I18N_NUMBERFORMATSYMBOLS_GROUP_SEP",l.I);b("I18N_NUMBERFORMATSYMBOLS_PERCENT",l.U);b("I18N_NUMBERFORMATSYMBOLS_ZERO_DIGIT",l.qa);b("I18N_NUMBERFORMATSYMBOLS_PLUS_SIGN",l.X);b("I18N_NUMBERFORMATSYMBOLS_MINUS_SIGN",l.K);b("I18N_NUMBERFORMATSYMBOLS_EXP_SYMBOL",l.F);b("I18N_NUMBERFORMATSYMBOLS_PERMILL",l.W);b("I18N_NUMBERFORMATSYMBOLS_INFINITY",l.J);b("I18N_NUMBERFORMATSYMBOLS_NAN",l.R);
b("I18N_NUMBERFORMATSYMBOLS_DECIMAL_PATTERN",l.v);b("I18N_NUMBERFORMATSYMBOLS_SCIENTIFIC_PATTERN",l.Z);b("I18N_NUMBERFORMATSYMBOLS_PERCENT_PATTERN",l.V);b("I18N_NUMBERFORMATSYMBOLS_CURRENCY_PATTERN",l.l);b("I18N_NUMBERFORMATSYMBOLS_DEF_CURRENCY_CODE",l.B);b("I18N_COMPACT_DECIMAL_SHORT_PATTERN",c.j);b("I18N_COMPACT_DECIMAL_LONG_PATTERN",c.i);
