/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var a=this||self,b=function(g,k){g=g.split(".");for(var f=a,e;g.length&&(e=g.shift());)g.length||k===void 0?f=f[e]&&f[e]!==Object.prototype[e]?f[e]:f[e]={}:f[e]=k};var c={j:{1E3:{other:"0K"},1E4:{other:"00K"},1E5:{other:"000K"},1E6:{other:"0M"},1E7:{other:"00M"},1E8:{other:"000M"},1E9:{other:"0B"},1E10:{other:"00B"},1E11:{other:"000B"},1E12:{other:"0T"},1E13:{other:"00T"},1E14:{other:"000T"}},i:{1E3:{other:"0 thousand"},1E4:{other:"00 thousand"},1E5:{other:"000 thousand"},1E6:{other:"0 million"},1E7:{other:"00 million"},1E8:{other:"000 million"},1E9:{other:"0 billion"},1E10:{other:"00 billion"},1E11:{other:"000 billion"},1E12:{other:"0 trillion"},1E13:{other:"00 trillion"},
1E14:{other:"000 trillion"}}};
c={j:{1E3:{other:"0"},1E4:{other:"0"},1E5:{other:"0"},1E6:{other:"0\u00a0M"},1E7:{other:"00\u00a0M"},1E8:{other:"000\u00a0M"},1E9:{other:"0000\u00a0M"},1E10:{other:"00000\u00a0M"},1E11:{other:"000000\u00a0M"},1E12:{other:"0\u00a0B"},1E13:{other:"00\u00a0B"},1E14:{other:"000\u00a0B"}},i:{1E3:{other:"0"},1E4:{other:"0"},1E5:{other:"0"},1E6:{other:"0 milioi"},1E7:{other:"00 milioi"},1E8:{other:"000 milioi"},1E9:{other:"0000 milioi"},1E10:{other:"00000 milioi"},1E11:{other:"000000 milioi"},1E12:{other:"0 bilioi"},
1E13:{other:"00 bilioi"},1E14:{other:"000 bilioi"}}};var d={na:"y",va:"y G",oa:"MMM y",pa:"MMMM y",wa:"MM/y",M:"MMM d",N:"MMMM dd",P:"M/d",O:"MMMM d",sa:"MMM d, y",la:"EEE, MMM d",ta:"EEEE, MMMM d",ua:"EEE, MMM d, y",u:"d",ra:"MMM d, h:mm\u202fa zzzz"};d={na:"y",va:"G y",oa:"y MMM",pa:"y('e')'ko' MMMM",wa:"y/MM",M:"MMM d('a')",N:"MMMM'ren' dd('a')",P:"M/d",O:"MMMM'ren' d('a')",sa:"y MMM d('a')",la:"MMM d('a'), EEE",ta:"MMMM d('a'), EEEE",ua:"y MMM d('a'), EEE",u:"d",ra:"MMM d('a') (HH:mm zzzz)"};var h={D:["BC","AD"],C:["Before Christ","Anno Domini"],S:"JFMAMJJASOND".split(""),ea:"JFMAMJJASOND".split(""),L:"January February March April May June July August September October November December".split(" "),da:"January February March April May June July August September October November December".split(" "),aa:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),ga:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),ka:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
ia:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),ca:"Sun Mon Tue Wed Thu Fri Sat".split(" "),ha:"Sun Mon Tue Wed Thu Fri Sat".split(" "),T:"SMTWTFS".split(""),fa:"SMTWTFS".split(""),ba:["Q1","Q2","Q3","Q4"],Y:["1st quarter","2nd quarter","3rd quarter","4th quarter"],h:["AM","PM"],m:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],ja:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],o:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],G:6,ma:[5,
6],H:5};
h={D:["K.a.","K.o."],C:["Kristo aurretik","Kristo ondoren"],S:"UOMAMEUAIUAA".split(""),ea:"UOMAMEUAIUAA".split(""),L:"urtarrila otsaila martxoa apirila maiatza ekaina uztaila abuztua iraila urria azaroa abendua".split(" "),da:"urtarrila otsaila martxoa apirila maiatza ekaina uztaila abuztua iraila urria azaroa abendua".split(" "),aa:"urt. ots. mar. api. mai. eka. uzt. abu. ira. urr. aza. abe.".split(" "),ga:"urt. ots. mar. api. mai. eka. uzt. abu. ira. urr. aza. abe.".split(" "),ka:"igandea astelehena asteartea asteazkena osteguna ostirala larunbata".split(" "),ia:"igandea astelehena asteartea asteazkena osteguna ostirala larunbata".split(" "),
ca:"ig. al. ar. az. og. or. lr.".split(" "),ha:"ig. al. ar. az. og. or. lr.".split(" "),T:"IAAAOOL".split(""),fa:"IAAAOOL".split(""),ba:["1Hh","2Hh","3Hh","4Hh"],Y:["1. hiruhilekoa","2. hiruhilekoa","3. hiruhilekoa","4. hiruhilekoa"],h:["AM","PM"],m:["y('e')'ko' MMMM'ren' d('a'), EEEE","y('e')'ko' MMMM'ren' d('a')","y('e')'ko' MMM d('a')","yy/M/d"],ja:["HH:mm:ss (zzzz)","HH:mm:ss (z)","HH:mm:ss","HH:mm"],o:["{1} ({0})","{1} ({0})","{1} ({0})","{1} ({0})"],G:0,ma:[5,6],H:3};var l={A:".",I:",",U:"%",qa:"0",X:"+",K:"-",F:"E",W:"\u2030",J:"\u221e",R:"NaN",v:"#,##0.###",Z:"#E0",V:"#,##0%",l:"\u00a4#,##0.00",B:"USD"};l={A:",",I:".",U:"%",qa:"0",X:"+",K:"\u2212",F:"E",W:"\u2030",J:"\u221e",R:"NaN",v:"#,##0.###",Z:"#E0",V:"%\u00a0#,##0",l:"#,##0.00\u00a0\u00a4",B:"EUR"};b("I18N_DATETIMESYMBOLS_ERAS",h.D);b("I18N_DATETIMESYMBOLS_ERANAMES",h.C);b("I18N_DATETIMESYMBOLS_NARROWMONTHS",h.S);b("I18N_DATETIMESYMBOLS_STANDALONENARROWMONTHS",h.ea);b("I18N_DATETIMESYMBOLS_MONTHS",h.L);b("I18N_DATETIMESYMBOLS_STANDALONEMONTHS",h.da);b("I18N_DATETIMESYMBOLS_SHORTMONTHS",h.aa);b("I18N_DATETIMESYMBOLS_STANDALONESHORTMONTHS",h.ga);b("I18N_DATETIMESYMBOLS_WEEKDAYS",h.ka);b("I18N_DATETIMESYMBOLS_STANDALONEWEEKDAYS",h.ia);b("I18N_DATETIMESYMBOLS_SHORTWEEKDAYS",h.ca);
b("I18N_DATETIMESYMBOLS_STANDALONESHORTWEEKDAYS",h.ha);b("I18N_DATETIMESYMBOLS_NARROWWEEKDAYS",h.T);b("I18N_DATETIMESYMBOLS_STANDALONENARROWWEEKDAYS",h.fa);b("I18N_DATETIMESYMBOLS_SHORTQUARTERS",h.ba);b("I18N_DATETIMESYMBOLS_QUARTERS",h.Y);b("I18N_DATETIMESYMBOLS_AMPMS",h.h);b("I18N_DATETIMESYMBOLS_DATEFORMATS",h.m);b("I18N_DATETIMESYMBOLS_TIMEFORMATS",h.ja);b("I18N_DATETIMESYMBOLS_DATETIMEFORMATS",h.o);b("I18N_DATETIMESYMBOLS_FIRSTDAYOFWEEK",h.G);b("I18N_DATETIMESYMBOLS_WEEKENDRANGE",h.ma);
b("I18N_DATETIMESYMBOLS_FIRSTWEEKCUTOFFDAY",h.H);b("I18N_DATETIMEPATTERNS_YEAR_FULL",d.na);b("I18N_DATETIMEPATTERNS_YEAR_MONTH_ABBR",d.oa);b("I18N_DATETIMEPATTERNS_YEAR_MONTH_FULL",d.pa);b("I18N_DATETIMEPATTERNS_MONTH_DAY_ABBR",d.M);b("I18N_DATETIMEPATTERNS_MONTH_DAY_FULL",d.N);b("I18N_DATETIMEPATTERNS_MONTH_DAY_SHORT",d.P);b("I18N_DATETIMEPATTERNS_MONTH_DAY_MEDIUM",d.O);b("I18N_DATETIMEPATTERNS_WEEKDAY_MONTH_DAY_MEDIUM",d.la);b("I18N_DATETIMEPATTERNS_DAY_ABBR",d.u);
h.xa!==void 0&&b("I18N_DATETIMESYMBOLS_ZERODIGIT",h.xa);b("I18N_NUMBERFORMATSYMBOLS_DECIMAL_SEP",l.A);b("I18N_NUMBERFORMATSYMBOLS_GROUP_SEP",l.I);b("I18N_NUMBERFORMATSYMBOLS_PERCENT",l.U);b("I18N_NUMBERFORMATSYMBOLS_ZERO_DIGIT",l.qa);b("I18N_NUMBERFORMATSYMBOLS_PLUS_SIGN",l.X);b("I18N_NUMBERFORMATSYMBOLS_MINUS_SIGN",l.K);b("I18N_NUMBERFORMATSYMBOLS_EXP_SYMBOL",l.F);b("I18N_NUMBERFORMATSYMBOLS_PERMILL",l.W);b("I18N_NUMBERFORMATSYMBOLS_INFINITY",l.J);b("I18N_NUMBERFORMATSYMBOLS_NAN",l.R);
b("I18N_NUMBERFORMATSYMBOLS_DECIMAL_PATTERN",l.v);b("I18N_NUMBERFORMATSYMBOLS_SCIENTIFIC_PATTERN",l.Z);b("I18N_NUMBERFORMATSYMBOLS_PERCENT_PATTERN",l.V);b("I18N_NUMBERFORMATSYMBOLS_CURRENCY_PATTERN",l.l);b("I18N_NUMBERFORMATSYMBOLS_DEF_CURRENCY_CODE",l.B);b("I18N_COMPACT_DECIMAL_SHORT_PATTERN",c.j);b("I18N_COMPACT_DECIMAL_LONG_PATTERN",c.i);
