/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var a=this||self,b=function(g,k){g=g.split(".");for(var f=a,e;g.length&&(e=g.shift());)g.length||k===void 0?f=f[e]&&f[e]!==Object.prototype[e]?f[e]:f[e]={}:f[e]=k};var c={qa:{1E3:{other:"0K"},1E4:{other:"00K"},1E5:{other:"000K"},1E6:{other:"0M"},1E7:{other:"00M"},1E8:{other:"000M"},1E9:{other:"0B"},1E10:{other:"00B"},1E11:{other:"000B"},1E12:{other:"0T"},1E13:{other:"00T"},1E14:{other:"000T"}},pa:{1E3:{other:"0 thousand"},1E4:{other:"00 thousand"},1E5:{other:"000 thousand"},1E6:{other:"0 million"},1E7:{other:"00 million"},1E8:{other:"000 million"},1E9:{other:"0 billion"},1E10:{other:"00 billion"},1E11:{other:"000 billion"},1E12:{other:"0 trillion"},1E13:{other:"00 trillion"},
1E14:{other:"000 trillion"}}},d=c;d=c;var h={la:"y",va:"y G",ma:"MMM y",na:"MMMM y",wa:"MM/y",K:"MMM d",L:"MMMM dd",N:"M/d",M:"MMMM d",sa:"MMM d, y",ja:"EEE, MMM d",ta:"EEEE, MMMM d",ua:"EEE, MMM d, y",m:"d",ra:"MMM d, h:mm\u202fa zzzz"};h={la:"y",va:"y G",ma:"MMM y",na:"MMMM y",wa:"y-MM",K:"MMM d",L:"MMMM dd",N:"MM-dd",M:"MMMM d",sa:"MMM d, y",ja:"EEE, MMM d",ta:"EEEE, MMMM d",ua:"EEE, MMM d, y",m:"d",ra:"MMM d, h:mm\u202fa zzzz"};var l={B:["BC","AD"],A:["Before Christ","Anno Domini"],P:"JFMAMJJASOND".split(""),ca:"JFMAMJJASOND".split(""),J:"January February March April May June July August September October November December".split(" "),ba:"January February March April May June July August September October November December".split(" "),Y:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),ea:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),ia:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
ga:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),aa:"Sun Mon Tue Wed Thu Fri Sat".split(" "),fa:"Sun Mon Tue Wed Thu Fri Sat".split(" "),R:"SMTWTFS".split(""),da:"SMTWTFS".split(""),Z:["Q1","Q2","Q3","Q4"],W:["1st quarter","2nd quarter","3rd quarter","4th quarter"],h:["AM","PM"],j:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],ha:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],l:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],D:6,ka:[5,
6],F:5};
l={B:["BC","AD"],A:["Before Christ","Anno Domini"],P:"JFMAMJJASOND".split(""),ca:"JFMAMJJASOND".split(""),J:"January February March April May June July August September October November December".split(" "),ba:"January February March April May June July August September October November December".split(" "),Y:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),ea:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),ia:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),ga:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
aa:"Sun Mon Tue Wed Thu Fri Sat".split(" "),fa:"Sun Mon Tue Wed Thu Fri Sat".split(" "),R:"SMTWTFS".split(""),da:"SMTWTFS".split(""),Z:["Q1","Q2","Q3","Q4"],W:["1st quarter","2nd quarter","3rd quarter","4th quarter"],h:["a.m.","p.m."],j:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","y-MM-dd"],ha:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],l:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],D:6,ka:[5,6],F:5};var m={u:".",G:",",S:"%",oa:"0",V:"+",I:"-",C:"E",U:"\u2030",H:"\u221e",O:"NaN",o:"#,##0.###",X:"#E0",T:"#,##0%",i:"\u00a4#,##0.00",v:"USD"};m={u:".",G:",",S:"%",oa:"0",V:"+",I:"-",C:"E",U:"\u2030",H:"\u221e",O:"NaN",o:"#,##0.###",X:"#E0",T:"#,##0%",i:"\u00a4#,##0.00",v:"CAD"};b("I18N_DATETIMESYMBOLS_ERAS",l.B);b("I18N_DATETIMESYMBOLS_ERANAMES",l.A);b("I18N_DATETIMESYMBOLS_NARROWMONTHS",l.P);b("I18N_DATETIMESYMBOLS_STANDALONENARROWMONTHS",l.ca);b("I18N_DATETIMESYMBOLS_MONTHS",l.J);b("I18N_DATETIMESYMBOLS_STANDALONEMONTHS",l.ba);b("I18N_DATETIMESYMBOLS_SHORTMONTHS",l.Y);b("I18N_DATETIMESYMBOLS_STANDALONESHORTMONTHS",l.ea);b("I18N_DATETIMESYMBOLS_WEEKDAYS",l.ia);b("I18N_DATETIMESYMBOLS_STANDALONEWEEKDAYS",l.ga);b("I18N_DATETIMESYMBOLS_SHORTWEEKDAYS",l.aa);
b("I18N_DATETIMESYMBOLS_STANDALONESHORTWEEKDAYS",l.fa);b("I18N_DATETIMESYMBOLS_NARROWWEEKDAYS",l.R);b("I18N_DATETIMESYMBOLS_STANDALONENARROWWEEKDAYS",l.da);b("I18N_DATETIMESYMBOLS_SHORTQUARTERS",l.Z);b("I18N_DATETIMESYMBOLS_QUARTERS",l.W);b("I18N_DATETIMESYMBOLS_AMPMS",l.h);b("I18N_DATETIMESYMBOLS_DATEFORMATS",l.j);b("I18N_DATETIMESYMBOLS_TIMEFORMATS",l.ha);b("I18N_DATETIMESYMBOLS_DATETIMEFORMATS",l.l);b("I18N_DATETIMESYMBOLS_FIRSTDAYOFWEEK",l.D);b("I18N_DATETIMESYMBOLS_WEEKENDRANGE",l.ka);
b("I18N_DATETIMESYMBOLS_FIRSTWEEKCUTOFFDAY",l.F);b("I18N_DATETIMEPATTERNS_YEAR_FULL",h.la);b("I18N_DATETIMEPATTERNS_YEAR_MONTH_ABBR",h.ma);b("I18N_DATETIMEPATTERNS_YEAR_MONTH_FULL",h.na);b("I18N_DATETIMEPATTERNS_MONTH_DAY_ABBR",h.K);b("I18N_DATETIMEPATTERNS_MONTH_DAY_FULL",h.L);b("I18N_DATETIMEPATTERNS_MONTH_DAY_SHORT",h.N);b("I18N_DATETIMEPATTERNS_MONTH_DAY_MEDIUM",h.M);b("I18N_DATETIMEPATTERNS_WEEKDAY_MONTH_DAY_MEDIUM",h.ja);b("I18N_DATETIMEPATTERNS_DAY_ABBR",h.m);
l.xa!==void 0&&b("I18N_DATETIMESYMBOLS_ZERODIGIT",l.xa);b("I18N_NUMBERFORMATSYMBOLS_DECIMAL_SEP",m.u);b("I18N_NUMBERFORMATSYMBOLS_GROUP_SEP",m.G);b("I18N_NUMBERFORMATSYMBOLS_PERCENT",m.S);b("I18N_NUMBERFORMATSYMBOLS_ZERO_DIGIT",m.oa);b("I18N_NUMBERFORMATSYMBOLS_PLUS_SIGN",m.V);b("I18N_NUMBERFORMATSYMBOLS_MINUS_SIGN",m.I);b("I18N_NUMBERFORMATSYMBOLS_EXP_SYMBOL",m.C);b("I18N_NUMBERFORMATSYMBOLS_PERMILL",m.U);b("I18N_NUMBERFORMATSYMBOLS_INFINITY",m.H);b("I18N_NUMBERFORMATSYMBOLS_NAN",m.O);
b("I18N_NUMBERFORMATSYMBOLS_DECIMAL_PATTERN",m.o);b("I18N_NUMBERFORMATSYMBOLS_SCIENTIFIC_PATTERN",m.X);b("I18N_NUMBERFORMATSYMBOLS_PERCENT_PATTERN",m.T);b("I18N_NUMBERFORMATSYMBOLS_CURRENCY_PATTERN",m.i);b("I18N_NUMBERFORMATSYMBOLS_DEF_CURRENCY_CODE",m.v);b("I18N_COMPACT_DECIMAL_SHORT_PATTERN",d.qa);b("I18N_COMPACT_DECIMAL_LONG_PATTERN",d.pa);
