/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var a=this||self,b=function(g,k){g=g.split(".");for(var f=a,e;g.length&&(e=g.shift());)g.length||k===void 0?f=f[e]&&f[e]!==Object.prototype[e]?f[e]:f[e]={}:f[e]=k};var c={j:{1E3:{other:"0K"},1E4:{other:"00K"},1E5:{other:"000K"},1E6:{other:"0M"},1E7:{other:"00M"},1E8:{other:"000M"},1E9:{other:"0B"},1E10:{other:"00B"},1E11:{other:"000B"},1E12:{other:"0T"},1E13:{other:"00T"},1E14:{other:"000T"}},i:{1E3:{other:"0 thousand"},1E4:{other:"00 thousand"},1E5:{other:"000 thousand"},1E6:{other:"0 million"},1E7:{other:"00 million"},1E8:{other:"000 million"},1E9:{other:"0 billion"},1E10:{other:"00 billion"},1E11:{other:"000 billion"},1E12:{other:"0 trillion"},1E13:{other:"00 trillion"},
1E14:{other:"000 trillion"}}},d=c;d=c;var h={na:"y",wa:"y G",oa:"MMM y",pa:"MMMM y",xa:"MM/y",M:"MMM d",N:"MMMM dd",P:"M/d",O:"MMMM d",ta:"MMM d, y",la:"EEE, MMM d",ua:"EEEE, MMMM d",va:"EEE, MMM d, y",u:"d",sa:"MMM d, h:mm\u202fa zzzz"},l=h;l=h;var m={D:["BC","AD"],C:["Before Christ","Anno Domini"],S:"JFMAMJJASOND".split(""),ea:"JFMAMJJASOND".split(""),L:"January February March April May June July August September October November December".split(" "),da:"January February March April May June July August September October November December".split(" "),aa:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),ga:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),ka:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
ia:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),ca:"Sun Mon Tue Wed Thu Fri Sat".split(" "),ha:"Sun Mon Tue Wed Thu Fri Sat".split(" "),T:"SMTWTFS".split(""),fa:"SMTWTFS".split(""),ba:["Q1","Q2","Q3","Q4"],Y:["1st quarter","2nd quarter","3rd quarter","4th quarter"],h:["AM","PM"],m:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],ja:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],o:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],G:6,ma:[5,
6],H:5},n=m;n=m;var p={A:".",I:",",U:"%",ra:"0",X:"+",K:"-",F:"E",W:"\u2030",J:"\u221e",R:"NaN",v:"#,##0.###",Z:"#E0",V:"#,##0%",l:"\u00a4#,##0.00",B:"USD"},q=p;q=p;b("I18N_DATETIMESYMBOLS_ERAS",n.D);b("I18N_DATETIMESYMBOLS_ERANAMES",n.C);b("I18N_DATETIMESYMBOLS_NARROWMONTHS",n.S);b("I18N_DATETIMESYMBOLS_STANDALONENARROWMONTHS",n.ea);b("I18N_DATETIMESYMBOLS_MONTHS",n.L);b("I18N_DATETIMESYMBOLS_STANDALONEMONTHS",n.da);b("I18N_DATETIMESYMBOLS_SHORTMONTHS",n.aa);b("I18N_DATETIMESYMBOLS_STANDALONESHORTMONTHS",n.ga);b("I18N_DATETIMESYMBOLS_WEEKDAYS",n.ka);b("I18N_DATETIMESYMBOLS_STANDALONEWEEKDAYS",n.ia);b("I18N_DATETIMESYMBOLS_SHORTWEEKDAYS",n.ca);
b("I18N_DATETIMESYMBOLS_STANDALONESHORTWEEKDAYS",n.ha);b("I18N_DATETIMESYMBOLS_NARROWWEEKDAYS",n.T);b("I18N_DATETIMESYMBOLS_STANDALONENARROWWEEKDAYS",n.fa);b("I18N_DATETIMESYMBOLS_SHORTQUARTERS",n.ba);b("I18N_DATETIMESYMBOLS_QUARTERS",n.Y);b("I18N_DATETIMESYMBOLS_AMPMS",n.h);b("I18N_DATETIMESYMBOLS_DATEFORMATS",n.m);b("I18N_DATETIMESYMBOLS_TIMEFORMATS",n.ja);b("I18N_DATETIMESYMBOLS_DATETIMEFORMATS",n.o);b("I18N_DATETIMESYMBOLS_FIRSTDAYOFWEEK",n.G);b("I18N_DATETIMESYMBOLS_WEEKENDRANGE",n.ma);
b("I18N_DATETIMESYMBOLS_FIRSTWEEKCUTOFFDAY",n.H);b("I18N_DATETIMEPATTERNS_YEAR_FULL",l.na);b("I18N_DATETIMEPATTERNS_YEAR_MONTH_ABBR",l.oa);b("I18N_DATETIMEPATTERNS_YEAR_MONTH_FULL",l.pa);b("I18N_DATETIMEPATTERNS_MONTH_DAY_ABBR",l.M);b("I18N_DATETIMEPATTERNS_MONTH_DAY_FULL",l.N);b("I18N_DATETIMEPATTERNS_MONTH_DAY_SHORT",l.P);b("I18N_DATETIMEPATTERNS_MONTH_DAY_MEDIUM",l.O);b("I18N_DATETIMEPATTERNS_WEEKDAY_MONTH_DAY_MEDIUM",l.la);b("I18N_DATETIMEPATTERNS_DAY_ABBR",l.u);
n.qa!==void 0&&b("I18N_DATETIMESYMBOLS_ZERODIGIT",n.qa);b("I18N_NUMBERFORMATSYMBOLS_DECIMAL_SEP",q.A);b("I18N_NUMBERFORMATSYMBOLS_GROUP_SEP",q.I);b("I18N_NUMBERFORMATSYMBOLS_PERCENT",q.U);b("I18N_NUMBERFORMATSYMBOLS_ZERO_DIGIT",q.ra);b("I18N_NUMBERFORMATSYMBOLS_PLUS_SIGN",q.X);b("I18N_NUMBERFORMATSYMBOLS_MINUS_SIGN",q.K);b("I18N_NUMBERFORMATSYMBOLS_EXP_SYMBOL",q.F);b("I18N_NUMBERFORMATSYMBOLS_PERMILL",q.W);b("I18N_NUMBERFORMATSYMBOLS_INFINITY",q.J);b("I18N_NUMBERFORMATSYMBOLS_NAN",q.R);
b("I18N_NUMBERFORMATSYMBOLS_DECIMAL_PATTERN",q.v);b("I18N_NUMBERFORMATSYMBOLS_SCIENTIFIC_PATTERN",q.Z);b("I18N_NUMBERFORMATSYMBOLS_PERCENT_PATTERN",q.V);b("I18N_NUMBERFORMATSYMBOLS_CURRENCY_PATTERN",q.l);b("I18N_NUMBERFORMATSYMBOLS_DEF_CURRENCY_CODE",q.B);b("I18N_COMPACT_DECIMAL_SHORT_PATTERN",d.j);b("I18N_COMPACT_DECIMAL_LONG_PATTERN",d.i);
